# Dev Containerではこちらが優先される。
services:
  rust_tutorial_app:
    build:
      target: devcontainer
      context: ./
      dockerfile: Dockerfile
    image: rust_devcontainer:latest
    container_name: rust_devcontainer_container
    volumes:
      - ./:/app # contextから見たパスではなく，リポジトリから見たパスがvolume mountされる。

